
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/restful_service}
    username: ${DB_USERNAME:DB_USERNAME}
    password: ${DB_PASSWORD:DB_PASSWORD}

  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/restful_service}
    user: ${DB_USERNAME:DB_USERNAME}
    password: ${DB_PASSWORD:DB_PASSWORD}
    enabled: true
    schemas: public
    locations: classpath:db/migration