CREATE TYPE "role" AS ENUM (
  'ROLE_USER',
  'ROLE_ADMIN'
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE "brand" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "model" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "gear_box" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "fuel" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "city" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "car_offer" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "seller" int NOT NULL,
  "brand" int NOT NULL,
  "model" int NOT NULL,
  "gear_box" int NOT NULL,
  "fuel" int NOT NULL,
  "city" int NOT NULL,
  "description" varchar(2000),
  "year" int NOT NULL,
  "mileage" int NOT NULL,
  "price" float NOT NULL,
  "delete" boolean
);

ALTER TABLE "car_offer" ADD FOREIGN KEY ("seller") REFERENCES "users" ("id");

ALTER TABLE "car_offer" ADD FOREIGN KEY ("brand") REFERENCES "brand" ("id");

ALTER TABLE "car_offer" ADD FOREIGN KEY ("model") REFERENCES "model" ("id");

ALTER TABLE "car_offer" ADD FOREIGN KEY ("gear_box") REFERENCES "gear_box" ("id");

ALTER TABLE "car_offer" ADD FOREIGN KEY ("fuel") REFERENCES "fuel" ("id");

ALTER TABLE "car_offer" ADD FOREIGN KEY ("city") REFERENCES "city" ("id");
