CREATE TYPE "role" AS ENUM (
  'ROLE_USER',
  'ROLE_ADMIN'
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE "brand" (
  "name" varchar(255) PRIMARY KEY NOT NULL
);

CREATE TABLE "model" (
  "name" varchar(255) PRIMARY KEY NOT NULL
);

CREATE TABLE "gear_box" (
  "type" varchar(255) PRIMARY KEY NOT NULL
);

CREATE TABLE "fuel" (
  "type" varchar(255) PRIMARY KEY NOT NULL
);

CREATE TABLE "city" (
  "name" varchar(255) PRIMARY KEY NOT NULL
);

CREATE TABLE "car_offer" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "seller_full_name" varchar(255) NOT NULL,
  "brand_name" varchar(255) NOT NULL,
  "model_name" varchar(255) NOT NULL,
  "gear_box_type" varchar(255) NOT NULL,
  "fuel_type" varchar(255) NOT NULL,
  "city_name" varchar(255) NOT NULL,
  "description" varchar(2000),
  "year" int NOT NULL,
  "mileage" int NOT NULL,
  "price" float NOT NULL,
  "delete" boolean
);

ALTER TABLE "car_offer" ADD FOREIGN KEY ("seller_full_name") REFERENCES "users" ("full_name");

ALTER TABLE "car_offer" ADD FOREIGN KEY ("brand_name") REFERENCES "brand" ("name");

ALTER TABLE "car_offer" ADD FOREIGN KEY ("model_name") REFERENCES "model" ("name");

ALTER TABLE "car_offer" ADD FOREIGN KEY ("gear_box_type") REFERENCES "gear_box" ("type");

ALTER TABLE "car_offer" ADD FOREIGN KEY ("fuel_type") REFERENCES "fuel" ("type");

ALTER TABLE "car_offer" ADD FOREIGN KEY ("city_name") REFERENCES "city" ("name");
